{"name": "test_new_order_show_in_list_in_progress", "status": "broken", "statusDetails": {"message": "AttributeError: 'OrderPage' object has no attribute 'execute'", "trace": "self = <tests.test_order_feed.TestOrderFeed object at 0x0000024486FFC710>, browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"7d2358af3da26a77ff9497ff9e8a37e5\")>\n\n    @allure.description('после оформления заказа его номер появляется в разделе В работе')\n    def test_new_order_show_in_list_in_progress(self, browser):\n        order_page = OrderPage(browser)\n        login_page = LoginPage(browser)\n        login_page.authorize()\n        source = order_page.find(cp.bay_burger)\n        target = order_page.find(cp.basket)\n>       order_page.drag_and_drop_method(source, target)\n\ntests\\test_order_feed.py:73: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\base_pages.py:33: in drag_and_drop_method\n    self.actions.drag_and_drop(source, target).perform()\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\action_chains.py:94: in perform\n    self.w3c_actions.perform()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.common.actions.action_builder.ActionBuilder object at 0x0000024486FFEAE0>\n\n    def perform(self) -> None:\n        enc = {\"actions\": []}\n        for device in self.devices:\n            encoded = device.encode()\n            if encoded[\"actions\"]:\n                enc[\"actions\"].append(encoded)\n                device.actions = []\n>       self.driver.execute(Command.W3C_ACTIONS, enc)\nE       AttributeError: 'OrderPage' object has no attribute 'execute'\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\actions\\action_builder.py:96: AttributeError"}, "description": "после оформления заказа его номер появляется в разделе В работе", "start": 1713371017034, "stop": 1713371018478, "uuid": "d2c91bc0-c286-4197-a0bd-4e3624f158aa", "historyId": "65662fa02eddfbe8bd41d4061b97259a", "testCaseId": "65662fa02eddfbe8bd41d4061b97259a", "fullName": "tests.test_order_feed.TestOrderFeed#test_new_order_show_in_list_in_progress", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed"}, {"name": "subSuite", "value": "TestOrderFeed"}, {"name": "host", "value": "DESKTOP-JATFUKA"}, {"name": "thread", "value": "13108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed"}]}